# Generated by Django 2.0.3 on 2018-04-03 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'NEW'), (2, 'PROCESSED'), (3, 'CLOSED'), (4, 'REOPEN'), (5, 'NOT A BUG')])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('priority', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('type', models.IntegerField(choices=[(1, 'ISSUE'), (2, 'FUTURE REQUEST')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Category')),
            ],
        ),
    ]
