# Generated by Django 2.0.3 on 2018-06-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20180403_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='labels',
            field=models.ManyToManyField(to='reports.Label'),
        ),
    ]
